### ISSUE TITLE
jquery-ui-slider-captcha not working 

### ISSUE THREAD

**Issue by bashabi** [ist-dsi/jquery-ui-slider-captcha#1]
Hi 

I have downloaded the Zip file. When I opened the index.html file in browser its not working. I have downloaded all the jquery file (which are not included in the ZIP folder) referenced in the index.html file.  
but the slider is not working. the slider is not movable. 
1. How can I make this work? Do you have a full sample folder available where the file is working properly.
2. Is it compatible with asp.net website?

looking forward to your response

**Comment by Kurmaev** [comment]
@bashabi, 
1. first of all you should make `bower install` to install all dependencies. Also you should edit `index.html` and change #19 row from
   `<script src="components/jQuery/dist/jquery.min.js?ver=0.1"></script>`
   to
   `<script src="components/jquery/dist/jquery.min.js?ver=0.1"></script>`
2. Yep, sure. It's just pure JS functional
